// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/auth/exists/[username].ts";
import * as $4 from "./routes/auth/generate-authentication-options.ts";
import * as $5 from "./routes/auth/generate-registration-options.ts";
import * as $6 from "./routes/auth/logout.ts";
import * as $7 from "./routes/auth/verify-authentication.ts";
import * as $8 from "./routes/auth/verify-registration.ts";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/ConfettiButtonIsland.tsx";
import * as $$1 from "./islands/UsernameButtonIsland.tsx";
import * as $$2 from "./islands/WebauthnPluginIsland.tsx";
import * as $$3 from "./islands/WebauthnLoginIsland.tsx";
import * as $$4 from "./islands/WebauthnLoginRegisterIsland.tsx";
import * as $$5 from "./islands/WebauthnRegisterIsland.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/auth/exists/[username].ts": $3,
    "./routes/auth/generate-authentication-options.ts": $4,
    "./routes/auth/generate-registration-options.ts": $5,
    "./routes/auth/logout.ts": $6,
    "./routes/auth/verify-authentication.ts": $7,
    "./routes/auth/verify-registration.ts": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/ConfettiButtonIsland.tsx": $$0,
    "./islands/UsernameButtonIsland.tsx": $$1,
    "./islands/WebatuhnPluginIsland.tsx": $$2,
    "./islands/WebauthnLoginIsland.tsx": $$3,
    "./islands/WebauthnLoginRegisterIsland.tsx": $$4,
    "./islands/WebauthnRegisterIsland.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
